### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@tim-werner, I need #3 (or #2) for https://github.com/conda-forge/azure-mgmt-datafactory-feedstock/pull/4.  It looks like you haven't had time to maintain this feedstock.  Would you be willing to merge this so I can become a maintainer and take care of #3?

**Comment by tim-werner** [comment]
you are welcone

**Comment by xylar** [comment]
Thank you kindly!

**Pull request merged**
